version: '3.4'

services:
  rentit.api:
    image: ${DOCKER_REGISTRY-}rentitapi
    build:
      context: .
      dockerfile: RentIt.Api/Dockerfile
    depends_on:
      - rentit-db

  rentit-db:
    image: postgres:latest
    container_name: RentIt.Db
    environment:
      - POSTGRES_DB=rentit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.container/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rentit-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: RentIt.Identity
    environment: 
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KEYCLOAK_IMPORT=/opt/keycloak/data/import/rentit-realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    command:
        - start-dev
    volumes:
        - ./.files:/opt/keycloak/data/import
        - ./.container/identity:/opt/keycloak/data
    ports:
        - 18080:8080    
  
  
